# Site settings
title: Kaizen IBBA
email: staff.ftc.ibba@gmail.com
description:
baseurl: "/" # the subpath of your site
url: "http://kaizenibba.com" # the base hostname & protocol for your site
timezone: America/Denver

# Site Author(s)
author:
  name: Daniel Jauch
  email: daniel.p.jauch@gmail.com

# Build settings
highlighter: pygments
markdown: kramdown
kramdown:
  auto_ids: true
  toc_levels: 1..6

# Permalinks

# Include Sub Pages
include: ['_pages']

# Blog Settings
# paginate: 10
# paginate_path: "/news/page:num/"

# Collections
collections:
  gallery:
    output: true
    permalink: /gallery/:title/
  staff:
    output: false
    permalink: /staff/:title/
  faqs:
    output: false
    permalink: /faq/:title/
  values:
    output: false
    permalink: /values/:title/
  programs:
    output: false
    permalink: /programs/:title/
  lineage:
    output: false
    permalink: /lineage/:title/

# Social Media
facebook: "https://www.facebook.com/ibba.fc/"
youtube: "https://www.youtube.com/channel/UCkcOTCK82WIFTDpETiy1OJQ"
# instagram: ""

# Google Analytics
google_analytics_tracking_id: "UA-102590261-1"

exclude: ["vendor","node_modules","package.json","Gemfile","gulpfile.js","*.scss"]
