# Site settings
title: Kaizen International Black Belt Academy
email: staff.ftc.ibba@gmail.com
description: "Kaizen IBBA"
keywords: "Kaizen, IBBA, International Black Belt Academy, Fort Collins, Karate, Martial Arts"
baseurl: "/" # the subpath of your site
url: "http://kaizenibba.com" # the base hostname & protocol for your site
timezone: America/Denver

# Site Author(s)
author:
  name: Daniel Jauch
  email: daniel.p.jauch@gmail.com

# Build settings
highlighter: pygments
markdown: kramdown
kramdown:
  auto_ids: true
  toc_levels: 1..6

# Permalinks

# Include Sub Pages
include: ['_pages']

# Blog Settings
# plugins: [jekyll-paginate]
# paginate: 5
# paginate_path: "/events/page:num/"
future: true

# Collections
collections:
  staff:
    output: false
  faqs:
    output: false
  values:
    output: false
  programs:
    output: false
  roots:
    output: false
  memberboxes:
    output: false
  gallery:
    output: true
    permalink: /gallery/:title/
  articles:
    output: true
    permalink: /events/:title/

# Social Media
facebook: "https://www.facebook.com/ibba.fc/"
youtube: "https://www.youtube.com/channel/UCkcOTCK82WIFTDpETiy1OJQ"
# instagram: ""

# Google Analytics
google_analytics_tracking_id: "UA-102590261-1"

exclude: ["vendor","node_modules","package.json","Gemfile","gulpfile.js","*.scss"]

#SEO Plugin
plugins_dir:
  - jekyll-seo-tag